/* GarageFlow â€” full schema, every migration, safe to re-run.

   Generated by:  dotnet ef migrations script --idempotent
   Regenerate:    deploy\generate-schema.ps1

   Each migration is guarded by a check against __EFMigrationsHistory, so
   running this against a database that is already up to date does nothing,
   and running it against one that is behind applies only what it is missing.

   QUOTED_IDENTIFIER must be ON: the Payments table carries a filtered unique
   index, and SQL Server refuses to create one without it. Set here rather
   than left to the client because sqlcmd is the one caller that defaults it
   OFF â€” running this file through sqlcmd without either this line or the -I
   flag fails with "CREATE INDEX failed because the following SET options
   have incorrect settings". SSMS and Azure Data Studio default it ON. */

SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_NULLS ON;
GO
IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE TABLE [Activities] (
        [Id] nvarchar(40) NOT NULL,
        [At] datetime2 NOT NULL,
        [Text] nvarchar(500) NOT NULL,
        [Kind] nvarchar(20) NOT NULL,
        CONSTRAINT [PK_Activities] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE TABLE [Customers] (
        [Id] nvarchar(20) NOT NULL,
        [Name] nvarchar(160) NOT NULL,
        [Phone] nvarchar(40) NOT NULL,
        [Email] nvarchar(160) NOT NULL,
        [Address] nvarchar(300) NOT NULL,
        [CreatedAt] date NOT NULL,
        [AvatarColor] nvarchar(40) NOT NULL,
        CONSTRAINT [PK_Customers] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE TABLE [Invoices] (
        [Id] nvarchar(20) NOT NULL,
        [JobCardId] nvarchar(20) NOT NULL,
        [CustomerId] nvarchar(20) NOT NULL,
        [CustomerName] nvarchar(160) NOT NULL,
        [VehiclePlate] nvarchar(40) NOT NULL,
        [IssuedAt] date NOT NULL,
        [Subtotal] decimal(18,2) NOT NULL,
        [TaxRate] decimal(9,4) NOT NULL,
        [Paid] decimal(18,2) NOT NULL,
        [Method] nvarchar(30) NULL,
        CONSTRAINT [PK_Invoices] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Invoices_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([Id]) ON DELETE NO ACTION
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE TABLE [Vehicles] (
        [Id] nvarchar(20) NOT NULL,
        [CustomerId] nvarchar(20) NOT NULL,
        [Make] nvarchar(80) NOT NULL,
        [Model] nvarchar(80) NOT NULL,
        [Year] int NOT NULL,
        [Plate] nvarchar(40) NOT NULL,
        [Vin] nvarchar(40) NOT NULL,
        [Fuel] nvarchar(20) NOT NULL,
        [Odometer] int NOT NULL,
        [Color] nvarchar(40) NOT NULL,
        CONSTRAINT [PK_Vehicles] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Vehicles_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE TABLE [Payments] (
        [Id] int NOT NULL IDENTITY,
        [InvoiceId] nvarchar(20) NOT NULL,
        [Amount] decimal(18,2) NOT NULL,
        [Method] nvarchar(30) NOT NULL,
        [At] datetime2 NOT NULL,
        CONSTRAINT [PK_Payments] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Payments_Invoices_InvoiceId] FOREIGN KEY ([InvoiceId]) REFERENCES [Invoices] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE TABLE [JobCards] (
        [Id] nvarchar(20) NOT NULL,
        [VehicleId] nvarchar(20) NOT NULL,
        [Complaint] nvarchar(1000) NOT NULL,
        [Status] nvarchar(20) NOT NULL,
        [Priority] nvarchar(20) NOT NULL,
        [Mechanic] nvarchar(120) NOT NULL,
        [Odometer] int NOT NULL,
        [CreatedAt] date NOT NULL,
        [PromisedAt] date NOT NULL,
        [CompletedAt] date NULL,
        CONSTRAINT [PK_JobCards] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_JobCards_Vehicles_VehicleId] FOREIGN KEY ([VehicleId]) REFERENCES [Vehicles] ([Id]) ON DELETE NO ACTION
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE TABLE [JobLines] (
        [Id] int NOT NULL IDENTITY,
        [JobCardId] nvarchar(20) NOT NULL,
        [Description] nvarchar(300) NOT NULL,
        [Qty] decimal(18,2) NOT NULL,
        [UnitPrice] decimal(18,2) NOT NULL,
        [Kind] nvarchar(20) NOT NULL,
        [SortOrder] int NOT NULL,
        CONSTRAINT [PK_JobLines] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_JobLines_JobCards_JobCardId] FOREIGN KEY ([JobCardId]) REFERENCES [JobCards] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Activities_At] ON [Activities] ([At]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Customers_Name] ON [Customers] ([Name]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Customers_Phone] ON [Customers] ([Phone]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Invoices_CustomerId] ON [Invoices] ([CustomerId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Invoices_IssuedAt] ON [Invoices] ([IssuedAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_JobCards_CreatedAt] ON [JobCards] ([CreatedAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_JobCards_Status] ON [JobCards] ([Status]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_JobCards_VehicleId] ON [JobCards] ([VehicleId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_JobLines_JobCardId] ON [JobLines] ([JobCardId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Payments_InvoiceId] ON [Payments] ([InvoiceId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Vehicles_CustomerId] ON [Vehicles] ([CustomerId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Vehicles_Plate] ON [Vehicles] ([Plate]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727090039_InitialCreate'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260727090039_InitialCreate', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727103844_AddAuthentication'
)
BEGIN
    CREATE TABLE [Users] (
        [Id] nvarchar(20) NOT NULL,
        [CompanyCode] nvarchar(40) NOT NULL,
        [Email] nvarchar(160) NOT NULL,
        [FullName] nvarchar(160) NOT NULL,
        [Phone] nvarchar(40) NULL,
        [PasswordHash] nvarchar(400) NOT NULL,
        [Role] nvarchar(20) NOT NULL,
        [Workshop] nvarchar(160) NOT NULL,
        [IsActive] bit NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [LastLoginAt] datetime2 NULL,
        [PasswordResetTokenHash] nvarchar(200) NULL,
        [PasswordResetExpiresAt] datetime2 NULL,
        CONSTRAINT [PK_Users] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727103844_AddAuthentication'
)
BEGIN
    CREATE TABLE [RefreshTokens] (
        [Id] int NOT NULL IDENTITY,
        [UserId] nvarchar(20) NOT NULL,
        [TokenHash] nvarchar(200) NOT NULL,
        [ExpiresAt] datetime2 NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [RevokedAt] datetime2 NULL,
        CONSTRAINT [PK_RefreshTokens] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_RefreshTokens_Users_UserId] FOREIGN KEY ([UserId]) REFERENCES [Users] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727103844_AddAuthentication'
)
BEGIN
    CREATE INDEX [IX_RefreshTokens_TokenHash] ON [RefreshTokens] ([TokenHash]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727103844_AddAuthentication'
)
BEGIN
    CREATE INDEX [IX_RefreshTokens_UserId] ON [RefreshTokens] ([UserId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727103844_AddAuthentication'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Users_CompanyCode_Email] ON [Users] ([CompanyCode], [Email]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260727103844_AddAuthentication'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260727103844_AddAuthentication', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728065040_AddVehicleType'
)
BEGIN
    ALTER TABLE [Vehicles] ADD [Type] nvarchar(20) NOT NULL DEFAULT N'Car';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728065040_AddVehicleType'
)
BEGIN
    EXEC(N'UPDATE Vehicles
    SET    Type = ''Bike''
    WHERE  Make IN (''Bajaj'', ''TVS'', ''Hero'', ''Hero Honda'', ''Royal Enfield'',
                    ''KTM'', ''Yamaha'', ''Vespa'', ''Aprilia'', ''Benelli'',
                    ''Crossfire'', ''Keeway'', ''CFMoto'');')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728065040_AddVehicleType'
)
BEGIN
    EXEC(N'UPDATE Vehicles
    SET    Type = ''Bike''
    WHERE  Type <> ''Bike''
    AND    (Model LIKE ''%Activa%''   OR Model LIKE ''%Pulsar%''
         OR Model LIKE ''%Splendor%'' OR Model LIKE ''%Shine%''
         OR Model LIKE ''%Unicorn%''  OR Model LIKE ''%Dio%''
         OR Model LIKE ''%Scooty%''   OR Model LIKE ''%Apache%''
         OR Model LIKE ''%Bullet%''   OR Model LIKE ''%Himalayan%''
         OR Model LIKE ''%Duke%''     OR Model LIKE ''%Jupiter%''
         OR Model LIKE ''%Burgman%''  OR Model LIKE ''%Ntorq%''
         OR Model LIKE ''%Raider%''   OR Model LIKE ''%Hornet%''
         OR Model LIKE ''%Fascino%''  OR Model LIKE ''%Gixxer%''
         OR Model LIKE ''%Intruder%'' OR Model LIKE ''%Vespa%''
         OR Model LIKE ''%Livo%''     OR Model LIKE ''%Fazer%''
         OR Model LIKE ''FZ%''        OR Model LIKE ''R15%''
         OR Model LIKE ''MT-%''       OR Model LIKE ''CB%''
         OR Model LIKE ''Ray %''      OR Model LIKE ''Access %'');')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728065040_AddVehicleType'
)
BEGIN
    EXEC(N'UPDATE Vehicles
    SET    Type = ''Truck''
    WHERE  Make IN (''Ashok Leyland'', ''Eicher'', ''BharatBenz'');')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728065040_AddVehicleType'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260728065040_AddVehicleType', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    ALTER TABLE [Users] ADD [CustomerId] nvarchar(20) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    ALTER TABLE [Users] ADD [MechanicName] nvarchar(120) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE TABLE [Bookings] (
        [Id] nvarchar(20) NOT NULL,
        [CustomerId] nvarchar(20) NOT NULL,
        [VehicleId] nvarchar(20) NOT NULL,
        [Complaint] nvarchar(1000) NOT NULL,
        [PreferredDate] date NOT NULL,
        [PreferredTime] nvarchar(60) NOT NULL,
        [Status] nvarchar(20) NOT NULL,
        [StaffNote] nvarchar(500) NULL,
        [JobCardId] nvarchar(20) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [RespondedAt] datetime2 NULL,
        CONSTRAINT [PK_Bookings] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Bookings_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_Bookings_JobCards_JobCardId] FOREIGN KEY ([JobCardId]) REFERENCES [JobCards] ([Id]) ON DELETE SET NULL,
        CONSTRAINT [FK_Bookings_Vehicles_VehicleId] FOREIGN KEY ([VehicleId]) REFERENCES [Vehicles] ([Id]) ON DELETE NO ACTION
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE TABLE [JobPhotos] (
        [Id] int NOT NULL IDENTITY,
        [JobCardId] nvarchar(20) NOT NULL,
        [Path] nvarchar(400) NOT NULL,
        [FileName] nvarchar(260) NOT NULL,
        [SizeBytes] bigint NOT NULL,
        [ContentType] nvarchar(100) NOT NULL,
        [Kind] nvarchar(20) NOT NULL,
        [Caption] nvarchar(300) NOT NULL,
        [UploadedBy] nvarchar(120) NOT NULL,
        [UploadedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_JobPhotos] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_JobPhotos_JobCards_JobCardId] FOREIGN KEY ([JobCardId]) REFERENCES [JobCards] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE TABLE [Notifications] (
        [Id] int NOT NULL IDENTITY,
        [UserId] nvarchar(20) NOT NULL,
        [Title] nvarchar(200) NOT NULL,
        [Body] nvarchar(600) NOT NULL,
        [Kind] nvarchar(20) NOT NULL,
        [EntityId] nvarchar(20) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [ReadAt] datetime2 NULL,
        CONSTRAINT [PK_Notifications] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Notifications_Users_UserId] FOREIGN KEY ([UserId]) REFERENCES [Users] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE INDEX [IX_Users_CustomerId] ON [Users] ([CustomerId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE INDEX [IX_Users_MechanicName] ON [Users] ([MechanicName]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE INDEX [IX_Bookings_CustomerId] ON [Bookings] ([CustomerId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE INDEX [IX_Bookings_JobCardId] ON [Bookings] ([JobCardId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE INDEX [IX_Bookings_Status] ON [Bookings] ([Status]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE INDEX [IX_Bookings_VehicleId] ON [Bookings] ([VehicleId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE INDEX [IX_JobPhotos_JobCardId] ON [JobPhotos] ([JobCardId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    CREATE INDEX [IX_Notifications_UserId_ReadAt] ON [Notifications] ([UserId], [ReadAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([Id]) ON DELETE SET NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260728085131_AddMobileApps'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260728085131_AddMobileApps', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    ALTER TABLE [JobLines] ADD [ServiceId] nvarchar(20) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    CREATE TABLE [Services] (
        [Id] nvarchar(20) NOT NULL,
        [Name] nvarchar(160) NOT NULL,
        [Description] nvarchar(500) NOT NULL,
        [Category] nvarchar(40) NOT NULL,
        [Price] decimal(18,2) NOT NULL,
        [DurationMinutes] int NOT NULL,
        [VehicleTypes] nvarchar(120) NOT NULL,
        [IsActive] bit NOT NULL,
        [IsBookable] bit NOT NULL,
        [CreatedAt] date NOT NULL,
        CONSTRAINT [PK_Services] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    CREATE TABLE [BookingServices] (
        [Id] int NOT NULL IDENTITY,
        [BookingId] nvarchar(20) NOT NULL,
        [ServiceId] nvarchar(20) NOT NULL,
        [QuotedPrice] decimal(18,2) NOT NULL,
        CONSTRAINT [PK_BookingServices] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_BookingServices_Bookings_BookingId] FOREIGN KEY ([BookingId]) REFERENCES [Bookings] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_BookingServices_Services_ServiceId] FOREIGN KEY ([ServiceId]) REFERENCES [Services] ([Id]) ON DELETE NO ACTION
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    CREATE INDEX [IX_JobLines_ServiceId] ON [JobLines] ([ServiceId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    CREATE UNIQUE INDEX [IX_BookingServices_BookingId_ServiceId] ON [BookingServices] ([BookingId], [ServiceId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    CREATE INDEX [IX_BookingServices_ServiceId] ON [BookingServices] ([ServiceId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    CREATE INDEX [IX_Services_Category] ON [Services] ([Category]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    CREATE INDEX [IX_Services_IsActive_IsBookable] ON [Services] ([IsActive], [IsBookable]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    ALTER TABLE [JobLines] ADD CONSTRAINT [FK_JobLines_Services_ServiceId] FOREIGN KEY ([ServiceId]) REFERENCES [Services] ([Id]) ON DELETE SET NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729050536_AddServiceCatalogue'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260729050536_AddServiceCatalogue', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    ALTER TABLE [Customers] ADD [Latitude] float NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    ALTER TABLE [Customers] ADD [Longitude] float NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    EXEC(N'UPDATE Customers
    SET Latitude = 27.6893,
        Longitude = 85.3436
    WHERE Id = ''CUS-001'' AND Address = ''Baneshwor, Kathmandu''
      AND Latitude IS NULL AND Longitude IS NULL;')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    EXEC(N'UPDATE Customers
    SET Latitude = 28.2096,
        Longitude = 83.9556
    WHERE Id = ''CUS-002'' AND Address = ''Lakeside, Pokhara''
      AND Latitude IS NULL AND Longitude IS NULL;')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    EXEC(N'UPDATE Customers
    SET Latitude = 27.6766,
        Longitude = 85.325
    WHERE Id = ''CUS-003'' AND Address = ''Patan, Lalitpur''
      AND Latitude IS NULL AND Longitude IS NULL;')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    EXEC(N'UPDATE Customers
    SET Latitude = 26.8065,
        Longitude = 87.2846
    WHERE Id = ''CUS-004'' AND Address = ''Dharan, Sunsari''
      AND Latitude IS NULL AND Longitude IS NULL;')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    EXEC(N'UPDATE Customers
    SET Latitude = 27.6789,
        Longitude = 85.2774
    WHERE Id = ''CUS-006'' AND Address = ''Kirtipur, Kathmandu''
      AND Latitude IS NULL AND Longitude IS NULL;')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    EXEC(N'UPDATE Customers
    SET Latitude = 27.671,
        Longitude = 85.4298
    WHERE Id = ''CUS-007'' AND Address = ''Bhaktapur''
      AND Latitude IS NULL AND Longitude IS NULL;')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729054621_AddCustomerLocation'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260729054621_AddCustomerLocation', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    ALTER TABLE [Payments] ADD [Channel] nvarchar(10) NOT NULL DEFAULT N'cash';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    ALTER TABLE [Payments] ADD [FailureReason] nvarchar(300) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    ALTER TABLE [Payments] ADD [InitiatedAt] datetime2 NOT NULL DEFAULT '0001-01-01T00:00:00.0000000';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    ALTER TABLE [Payments] ADD [ProviderRef] nvarchar(120) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    ALTER TABLE [Payments] ADD [Reference] nvarchar(64) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    ALTER TABLE [Payments] ADD [Status] nvarchar(20) NOT NULL DEFAULT N'Completed';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    CREATE TABLE [Workshops] (
        [CompanyCode] nvarchar(40) NOT NULL,
        [Name] nvarchar(160) NOT NULL,
        [LegalName] nvarchar(200) NOT NULL,
        [Address] nvarchar(300) NOT NULL,
        [Phone] nvarchar(40) NOT NULL,
        [Email] nvarchar(160) NOT NULL,
        [TaxNumber] nvarchar(40) NOT NULL,
        [Latitude] float NULL,
        [Longitude] float NULL,
        [InvoiceFooter] nvarchar(500) NOT NULL,
        [OpeningHours] nvarchar(200) NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_Workshops] PRIMARY KEY ([CompanyCode])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    EXEC(N'CREATE UNIQUE INDEX [IX_Payments_Reference] ON [Payments] ([Reference]) WHERE [Reference] IS NOT NULL');
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    CREATE INDEX [IX_Payments_Status_Channel] ON [Payments] ([Status], [Channel]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    EXEC(N'UPDATE Payments SET Channel = ''bank''
    WHERE Method IN (''Bank Transfer'', ''Card'');

    UPDATE Payments SET Channel = ''online''
    WHERE Method IN (''eSewa'', ''Khalti'');')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    EXEC(N'UPDATE Payments SET InitiatedAt = At;')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729071414_AddWorkshopAndPaymentChannels'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260729071414_AddWorkshopAndPaymentChannels', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    ALTER TABLE [Workshops] ADD [DeliveryBaseFee] decimal(18,2) NOT NULL DEFAULT 50.0;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    ALTER TABLE [Workshops] ADD [DeliveryEnabled] bit NOT NULL DEFAULT CAST(1 AS bit);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    ALTER TABLE [Workshops] ADD [DeliveryFreeAbove] decimal(18,2) NOT NULL DEFAULT 5000.0;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    ALTER TABLE [Workshops] ADD [DeliveryMaxKm] float NOT NULL DEFAULT 15.0E0;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    ALTER TABLE [Workshops] ADD [DeliveryPerKm] decimal(18,2) NOT NULL DEFAULT 20.0;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE TABLE [CustomerRegistrations] (
        [Id] int NOT NULL IDENTITY,
        [CustomerId] nvarchar(20) NOT NULL,
        [CompanyCode] nvarchar(40) NOT NULL,
        [Contact] nvarchar(160) NOT NULL,
        [CodeHash] nvarchar(100) NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [ExpiresAt] datetime2 NOT NULL,
        [Attempts] int NOT NULL,
        [ConsumedAt] datetime2 NULL,
        CONSTRAINT [PK_CustomerRegistrations] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_CustomerRegistrations_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE TABLE [Deliveries] (
        [Id] nvarchar(20) NOT NULL,
        [JobCardId] nvarchar(20) NOT NULL,
        [CustomerId] nvarchar(20) NOT NULL,
        [Method] nvarchar(20) NOT NULL,
        [Status] nvarchar(20) NOT NULL,
        [Address] nvarchar(300) NOT NULL,
        [Latitude] float NULL,
        [Longitude] float NULL,
        [DistanceKm] float NULL,
        [Fee] decimal(18,2) NOT NULL,
        [Driver] nvarchar(120) NOT NULL,
        [DriverLatitude] float NULL,
        [DriverLongitude] float NULL,
        [DriverAt] datetime2 NULL,
        [CreatedAt] datetime2 NOT NULL,
        [ChosenAt] datetime2 NULL,
        [StartedAt] datetime2 NULL,
        [CompletedAt] datetime2 NULL,
        CONSTRAINT [PK_Deliveries] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Deliveries_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_Deliveries_JobCards_JobCardId] FOREIGN KEY ([JobCardId]) REFERENCES [JobCards] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE TABLE [DeliveryPoints] (
        [Id] int NOT NULL IDENTITY,
        [DeliveryId] nvarchar(20) NOT NULL,
        [Latitude] float NOT NULL,
        [Longitude] float NOT NULL,
        [AccuracyMetres] float NULL,
        [At] datetime2 NOT NULL,
        CONSTRAINT [PK_DeliveryPoints] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_DeliveryPoints_Deliveries_DeliveryId] FOREIGN KEY ([DeliveryId]) REFERENCES [Deliveries] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE INDEX [IX_CustomerRegistrations_CompanyCode_Contact] ON [CustomerRegistrations] ([CompanyCode], [Contact]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE INDEX [IX_CustomerRegistrations_CustomerId] ON [CustomerRegistrations] ([CustomerId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE INDEX [IX_Deliveries_CustomerId] ON [Deliveries] ([CustomerId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Deliveries_JobCardId] ON [Deliveries] ([JobCardId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE INDEX [IX_Deliveries_Status] ON [Deliveries] ([Status]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    CREATE INDEX [IX_DeliveryPoints_DeliveryId_At] ON [DeliveryPoints] ([DeliveryId], [At]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260729084502_AddDeliveriesAndRegistration'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260729084502_AddDeliveriesAndRegistration', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    ALTER TABLE [Workshops] ADD [About] nvarchar(600) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    ALTER TABLE [Workshops] ADD [IsListed] bit NOT NULL DEFAULT CAST(0 AS bit);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    CREATE TABLE [UserWorkshopLinks] (
        [Id] int NOT NULL IDENTITY,
        [UserId] nvarchar(20) NOT NULL,
        [CompanyCode] nvarchar(40) NOT NULL,
        [CustomerId] nvarchar(20) NOT NULL,
        [IsPrimary] bit NOT NULL,
        [JoinedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_UserWorkshopLinks] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_UserWorkshopLinks_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customers] ([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_UserWorkshopLinks_Users_UserId] FOREIGN KEY ([UserId]) REFERENCES [Users] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    CREATE INDEX [IX_Workshops_IsListed] ON [Workshops] ([IsListed]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    CREATE INDEX [IX_UserWorkshopLinks_CustomerId] ON [UserWorkshopLinks] ([CustomerId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    CREATE UNIQUE INDEX [IX_UserWorkshopLinks_UserId_CompanyCode] ON [UserWorkshopLinks] ([UserId], [CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    EXEC(N'INSERT INTO UserWorkshopLinks (UserId, CompanyCode, CustomerId, IsPrimary, JoinedAt)
    SELECT u.Id, u.CompanyCode, u.CustomerId, 1, u.CreatedAt
    FROM Users u
    WHERE u.Role = ''Customer''
      AND u.CustomerId IS NOT NULL
      AND u.CompanyCode <> ''''
      AND NOT EXISTS (
          SELECT 1 FROM UserWorkshopLinks l
          WHERE l.UserId = u.Id AND l.CompanyCode = u.CompanyCode);')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    EXEC(N'UPDATE Workshops SET IsListed = 1 WHERE CompanyCode = ''DEMO'';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730040211_AddCustomerMemberships'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260730040211_AddCustomerMemberships', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730070607_AddWorkspaceSession'
)
BEGIN
    ALTER TABLE [Users] ADD [BranchId] nvarchar(20) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730070607_AddWorkspaceSession'
)
BEGIN
    ALTER TABLE [Users] ADD [FiscalYear] nvarchar(20) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730070607_AddWorkspaceSession'
)
BEGIN
    CREATE TABLE [Branches] (
        [Id] nvarchar(20) NOT NULL,
        [CompanyCode] nvarchar(40) NOT NULL,
        [Name] nvarchar(160) NOT NULL,
        [Address] nvarchar(300) NOT NULL,
        [Phone] nvarchar(40) NOT NULL,
        [IsDefault] bit NOT NULL,
        [IsActive] bit NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_Branches] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730070607_AddWorkspaceSession'
)
BEGIN
    CREATE INDEX [IX_Branches_CompanyCode_IsActive] ON [Branches] ([CompanyCode], [IsActive]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730070607_AddWorkspaceSession'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260730070607_AddWorkspaceSession', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730091457_AddUserPhoto'
)
BEGIN
    ALTER TABLE [Users] ADD [PhotoPath] nvarchar(300) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260730091457_AddUserPhoto'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260730091457_AddUserPhoto', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731060336_AddWorkshopBankDetails'
)
BEGIN
    ALTER TABLE [Workshops] ADD [BankAccountName] nvarchar(160) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731060336_AddWorkshopBankDetails'
)
BEGIN
    ALTER TABLE [Workshops] ADD [BankAccountNumber] nvarchar(60) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731060336_AddWorkshopBankDetails'
)
BEGIN
    ALTER TABLE [Workshops] ADD [BankBranch] nvarchar(120) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731060336_AddWorkshopBankDetails'
)
BEGIN
    ALTER TABLE [Workshops] ADD [BankName] nvarchar(120) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731060336_AddWorkshopBankDetails'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260731060336_AddWorkshopBankDetails', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Vehicles] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Services] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Payments] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Notifications] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [JobLines] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [JobCards] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Invoices] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Deliveries] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Customers] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Bookings] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    ALTER TABLE [Activities] ADD [CompanyCode] nvarchar(40) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Customers] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Vehicles] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [JobCards] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [JobLines] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Invoices] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Payments] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Bookings] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Deliveries] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Services] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Activities] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    EXEC(N'UPDATE [Notifications] SET CompanyCode = ''DEMO'' WHERE CompanyCode = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Vehicles_CompanyCode] ON [Vehicles] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Services_CompanyCode] ON [Services] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Payments_CompanyCode] ON [Payments] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Notifications_CompanyCode] ON [Notifications] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_JobLines_CompanyCode] ON [JobLines] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_JobCards_CompanyCode] ON [JobCards] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Invoices_CompanyCode] ON [Invoices] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Deliveries_CompanyCode] ON [Deliveries] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Customers_CompanyCode] ON [Customers] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Bookings_CompanyCode] ON [Bookings] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    CREATE INDEX [IX_Activities_CompanyCode] ON [Activities] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731064615_AddTenantIsolation'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260731064615_AddTenantIsolation', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731070853_AddSuperAdminConsole'
)
BEGIN
    ALTER TABLE [Workshops] ADD [CreatedAt] datetime2 NOT NULL DEFAULT '0001-01-01T00:00:00.0000000';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731070853_AddSuperAdminConsole'
)
BEGIN
    ALTER TABLE [Workshops] ADD [EnabledModules] nvarchar(max) NOT NULL DEFAULT N'';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731070853_AddSuperAdminConsole'
)
BEGIN
    ALTER TABLE [Workshops] ADD [IsActive] bit NOT NULL DEFAULT CAST(0 AS bit);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731070853_AddSuperAdminConsole'
)
BEGIN
    CREATE TABLE [ImpersonationLogs] (
        [Id] int NOT NULL IDENTITY,
        [UserId] nvarchar(20) NOT NULL,
        [UserEmail] nvarchar(160) NOT NULL,
        [CompanyCode] nvarchar(40) NOT NULL,
        [At] datetime2 NOT NULL,
        [Reason] nvarchar(300) NOT NULL,
        CONSTRAINT [PK_ImpersonationLogs] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731070853_AddSuperAdminConsole'
)
BEGIN
    CREATE INDEX [IX_ImpersonationLogs_CompanyCode_At] ON [ImpersonationLogs] ([CompanyCode], [At]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731070853_AddSuperAdminConsole'
)
BEGIN
    EXEC(N'UPDATE Workshops SET EnabledModules = ''services,billing,reports,serviceHistory,staff,deliveries,fiscalYear,multiBranch,onlineBooking,onlinePayment'' WHERE EnabledModules IS NULL OR EnabledModules = '''';')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731070853_AddSuperAdminConsole'
)
BEGIN
    EXEC(N'UPDATE Workshops SET IsActive = 1;')
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731070853_AddSuperAdminConsole'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260731070853_AddSuperAdminConsole', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731103716_AddMenus'
)
BEGIN
    CREATE TABLE [MenuItems] (
        [Id] int NOT NULL IDENTITY,
        [Key] nvarchar(40) NOT NULL,
        [Label] nvarchar(80) NOT NULL,
        [LabelNe] nvarchar(80) NOT NULL,
        [Route] nvarchar(120) NOT NULL,
        [Icon] nvarchar(60) NOT NULL,
        [ParentKey] nvarchar(40) NULL,
        [SortOrder] int NOT NULL,
        [Module] nvarchar(40) NULL,
        [IsActive] bit NOT NULL,
        [IsLocked] bit NOT NULL,
        CONSTRAINT [PK_MenuItems] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731103716_AddMenus'
)
BEGIN
    CREATE TABLE [RoleMenus] (
        [Id] int NOT NULL IDENTITY,
        [CompanyCode] nvarchar(40) NOT NULL,
        [Role] nvarchar(20) NOT NULL,
        [MenuKey] nvarchar(40) NOT NULL,
        [CanView] bit NOT NULL,
        CONSTRAINT [PK_RoleMenus] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731103716_AddMenus'
)
BEGIN
    CREATE UNIQUE INDEX [IX_MenuItems_Key] ON [MenuItems] ([Key]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731103716_AddMenus'
)
BEGIN
    CREATE INDEX [IX_RoleMenus_CompanyCode] ON [RoleMenus] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731103716_AddMenus'
)
BEGIN
    CREATE UNIQUE INDEX [IX_RoleMenus_CompanyCode_Role_MenuKey] ON [RoleMenus] ([CompanyCode], [Role], [MenuKey]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731103716_AddMenus'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260731103716_AddMenus', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731110104_AddFiscalYearRecords'
)
BEGIN
    CREATE TABLE [FiscalYears] (
        [Id] int NOT NULL IDENTITY,
        [CompanyCode] nvarchar(40) NOT NULL,
        [Code] nvarchar(20) NOT NULL,
        [Start] date NOT NULL,
        [End] date NOT NULL,
        [IsClosed] bit NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_FiscalYears] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731110104_AddFiscalYearRecords'
)
BEGIN
    CREATE INDEX [IX_FiscalYears_CompanyCode] ON [FiscalYears] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731110104_AddFiscalYearRecords'
)
BEGIN
    CREATE UNIQUE INDEX [IX_FiscalYears_CompanyCode_Code] ON [FiscalYears] ([CompanyCode], [Code]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260731110104_AddFiscalYearRecords'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260731110104_AddFiscalYearRecords', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260802085909_AddCompanyRoles'
)
BEGIN
    ALTER TABLE [Users] ADD [CompanyRoleName] nvarchar(40) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260802085909_AddCompanyRoles'
)
BEGIN
    DROP INDEX [IX_RoleMenus_CompanyCode_Role_MenuKey] ON [RoleMenus];
    DECLARE @var nvarchar(max);
    SELECT @var = QUOTENAME([d].[name])
    FROM [sys].[default_constraints] [d]
    INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
    WHERE ([d].[parent_object_id] = OBJECT_ID(N'[RoleMenus]') AND [c].[name] = N'Role');
    IF @var IS NOT NULL EXEC(N'ALTER TABLE [RoleMenus] DROP CONSTRAINT ' + @var + ';');
    ALTER TABLE [RoleMenus] ALTER COLUMN [Role] nvarchar(40) NOT NULL;
    CREATE UNIQUE INDEX [IX_RoleMenus_CompanyCode_Role_MenuKey] ON [RoleMenus] ([CompanyCode], [Role], [MenuKey]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260802085909_AddCompanyRoles'
)
BEGIN
    CREATE TABLE [CompanyRoles] (
        [Id] int NOT NULL IDENTITY,
        [CompanyCode] nvarchar(40) NOT NULL,
        [Name] nvarchar(40) NOT NULL,
        [BaseRole] nvarchar(20) NOT NULL,
        [Description] nvarchar(200) NOT NULL,
        [IsBuiltIn] bit NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_CompanyRoles] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260802085909_AddCompanyRoles'
)
BEGIN
    CREATE INDEX [IX_CompanyRoles_CompanyCode] ON [CompanyRoles] ([CompanyCode]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260802085909_AddCompanyRoles'
)
BEGIN
    CREATE UNIQUE INDEX [IX_CompanyRoles_CompanyCode_Name] ON [CompanyRoles] ([CompanyCode], [Name]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260802085909_AddCompanyRoles'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260802085909_AddCompanyRoles', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260802111108_AddMustSetPassword'
)
BEGIN
    ALTER TABLE [Users] ADD [MustSetPassword] bit NOT NULL DEFAULT CAST(0 AS bit);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260802111108_AddMustSetPassword'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260802111108_AddMustSetPassword', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260803100053_ResetPasswordByCode'
)
BEGIN
    EXEC sp_rename N'[Users].[PasswordResetTokenHash]', N'PasswordResetCodeHash', 'COLUMN';
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260803100053_ResetPasswordByCode'
)
BEGIN
    ALTER TABLE [Users] ADD [PasswordResetAttempts] int NOT NULL DEFAULT 0;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260803100053_ResetPasswordByCode'
)
BEGIN
    ALTER TABLE [Users] ADD [PasswordResetSentAt] datetime2 NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260803100053_ResetPasswordByCode'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260803100053_ResetPasswordByCode', N'10.0.10');
END;

COMMIT;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260804043320_CompanyLogo'
)
BEGIN
    ALTER TABLE [Workshops] ADD [LogoPath] nvarchar(300) NULL;
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260804043320_CompanyLogo'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260804043320_CompanyLogo', N'10.0.10');
END;

COMMIT;
GO


