# Regenerates deploy/01-schema.sql from the current migrations.
#
# Run this after adding a migration, or the deployment script and the code
# disagree — and the way you find out is a production request failing on a
# column that only exists on your laptop.
#
#     pwsh deploy\generate-schema.ps1
#
# The header this prepends is not decoration. `dotnet ef migrations script`
# emits the filtered index on Payments inside an EXEC(), and SQL Server will
# not create a filtered index unless QUOTED_IDENTIFIER is ON. sqlcmd is the
# one client that defaults it OFF, so a script without the header fails for
# anyone deploying that way and works for everyone testing in SSMS.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$project = Join-Path $root 'src\GarageFlow.Api\GarageFlow.Api.csproj'
$output = Join-Path $PSScriptRoot '01-schema.sql'

Write-Host 'Building, so dotnet ef reads the current migrations...' -ForegroundColor Cyan

# `dotnet ef` loads the *built* assembly, not the .cs files. Without this a
# migration added since the last build is silently missing from the script.
Get-Process GarageFlow.Api -ErrorAction SilentlyContinue | Stop-Process -Force
dotnet build $project -v q --nologo | Out-Null

Write-Host 'Generating the idempotent script...' -ForegroundColor Cyan
dotnet ef migrations script --idempotent --project $project --no-build --output $output

$header = @'
/* GarageFlow — full schema, every migration, safe to re-run.

   Generated by:  dotnet ef migrations script --idempotent
   Regenerate:    deploy\generate-schema.ps1

   Each migration is guarded by a check against __EFMigrationsHistory, so
   running this against a database that is already up to date does nothing,
   and running it against one that is behind applies only what it is missing.

   QUOTED_IDENTIFIER must be ON: the Payments table carries a filtered unique
   index, and SQL Server refuses to create one without it. Set here rather
   than left to the client because sqlcmd is the one caller that defaults it
   OFF — running this file through sqlcmd without either this line or the -I
   flag fails with "CREATE INDEX failed because the following SET options
   have incorrect settings". SSMS and Azure Data Studio default it ON. */

SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_NULLS ON;
GO

'@

Set-Content -Path $output -Value ($header + (Get-Content $output -Raw)) -Encoding utf8

$lines = (Get-Content $output).Count
Write-Host "Wrote $output ($lines lines)." -ForegroundColor Green
Write-Host 'Test it against a scratch database before you ship it:' -ForegroundColor Yellow
Write-Host '  sqlcmd -S <server> -d <scratch-db> -i deploy\01-schema.sql -b'
